language: php
php:
 - '8.2'

services:
 - mysql

env:
 global:
  - MYSQL_DATABASE=symfony
  - MYSQL_ROOT_PASSWORD=root

before_script:
 - composer install --no-interaction --prefer-dist
 - php bin/console doctrine:database:create
 - php bin/console doctrine:migrations:migrate --no-interaction

script:
 - vendor/bin/phpunit
