name: CI Symfony

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # ✅ Ici on vérifie que les fichiers de tests sont bien présents
      - name: Lister les tests
        run: ls -R tests

      - name: Create test database
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:create --env=test

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Debug jeux et tags
        run: |
          php bin/console doctrine:query:sql "SELECT title FROM video_game;" --env=test
          php bin/console doctrine:query:sql "SELECT name FROM tag;" --env=test


      # ✅ Et ici on lance PHPUnit en utilisant ton phpunit.xml.dist
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --verbose

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --memory-limit=1G